# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treeview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(303, 452)
        Form.setWindowTitle("标题预览")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/plugin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("标题长度超")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.limit_lineEdit = LenLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.limit_lineEdit.sizePolicy().hasHeightForWidth())
        self.limit_lineEdit.setSizePolicy(sizePolicy)
        self.limit_lineEdit.setMinimumSize(QtCore.QSize(30, 18))
        self.limit_lineEdit.setMaximumSize(QtCore.QSize(30, 18))
        self.limit_lineEdit.setInputMask("")
        self.limit_lineEdit.setText("")
        self.limit_lineEdit.setPlaceholderText("")
        self.limit_lineEdit.setObjectName("limit_lineEdit")
        self.horizontalLayout_2.addWidget(self.limit_lineEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("显高亮")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ChapterLengthCheck_pbtn = QtWidgets.QPushButton(Form)
        self.ChapterLengthCheck_pbtn.setMinimumSize(QtCore.QSize(100, 0))
        self.ChapterLengthCheck_pbtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ChapterLengthCheck_pbtn.setObjectName("ChapterLengthCheck_pbtn")
        self.horizontalLayout_2.addWidget(self.ChapterLengthCheck_pbtn)
        self.horizontalLayout_2.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(3, 0, 5, 5)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setText("断序检查  ")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.seqCheckSwitch = QtWidgets.QPushButton(Form)
        self.seqCheckSwitch.setMinimumSize(QtCore.QSize(50, 0))
        self.seqCheckSwitch.setMaximumSize(QtCore.QSize(60, 16777215))
        self.seqCheckSwitch.setText("OFF")
        self.seqCheckSwitch.setCheckable(False)
        self.seqCheckSwitch.setObjectName("seqCheckSwitch")
        self.horizontalLayout.addWidget(self.seqCheckSwitch)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.FoldAll_pbtn = QtWidgets.QPushButton(Form)
        self.FoldAll_pbtn.setMinimumSize(QtCore.QSize(48, 0))
        self.FoldAll_pbtn.setMaximumSize(QtCore.QSize(48, 16777215))
        self.FoldAll_pbtn.setObjectName("FoldAll_pbtn")
        self.horizontalLayout.addWidget(self.FoldAll_pbtn)
        self.ExpandAll_pbtn = QtWidgets.QPushButton(Form)
        self.ExpandAll_pbtn.setMinimumSize(QtCore.QSize(48, 0))
        self.ExpandAll_pbtn.setMaximumSize(QtCore.QSize(48, 16777215))
        self.ExpandAll_pbtn.setObjectName("ExpandAll_pbtn")
        self.horizontalLayout.addWidget(self.ExpandAll_pbtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.title_tree = PreviewTreeWidget(Form)
        self.title_tree.setStyleSheet("")
        self.title_tree.setAlternatingRowColors(True)
        self.title_tree.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.title_tree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.title_tree.setIndentation(10)
        self.title_tree.setAnimated(False)
        self.title_tree.setObjectName("title_tree")
        self.title_tree.headerItem().setText(0, "1")
        self.title_tree.header().setVisible(False)
        self.verticalLayout.addWidget(self.title_tree)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.ChapterLengthCheck_pbtn.setText(_translate("Form", " 章节字数检查 "))
        self.FoldAll_pbtn.setText(_translate("Form", "折叠"))
        self.ExpandAll_pbtn.setText(_translate("Form", "展开"))
from widget_class.LenLineEdit import LenLineEdit
from widget_class.PreviewTreeWidget import PreviewTreeWidget
import res_rc
