// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogContent():Promise<string>;

export function OpenLogFile():Promise<string>;

export function RunTask(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SelectDir():Promise<string>;

export function SelectFiles():Promise<Array<string>>;
