// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogContent() {
  return window['go']['main']['App']['GetLogContent']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function RunTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunTask'](arg1, arg2, arg3, arg4);
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
